server:
 port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Suman25p/ecommerce_microservices_config_server.git
          default-label: main
          clone-on-start: true 